### ISSUE TITLE
ClausIE.get_instance() failed(NameError: name 'basestring' is not defined)

### ISSUE THREAD

**Issue by Bobyuan1015** [AnthonyMRios/pyclausie#1]
>>> cl = ClausIE.get_instance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 107, in get_instance
    return SubprocessBackend(**extra_args)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/SubprocessBackend.py", line 28, in __init__
    version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 53, in __init__
    self.download_if_missing(version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 75, in download_if_missing
    jar_url = self.get_jar_url(version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 90, in get_jar_url
    if not isinstance(version, basestring):
NameError: name 'basestring' is not defined
>>> cl = ClausIE.get_instance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 107, in get_instance
    return SubprocessBackend(**extra_args)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/SubprocessBackend.py", line 28, in __init__
    version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 53, in __init__
    self.download_if_missing(version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 75, in download_if_missing
    jar_url = self.get_jar_url(version)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/python3ClausIE/pyclausie/pyclausie/ClausIE.py", line 90, in get_jar_url
    if not isinstance(version, basestring):
NameError: name 'basestring' is not defined
>>>

**Comment by Bobyuan1015** [comment]
solved by replace 'basestring' to 'str'.


The solution is from "The builtin basestring abstract type was removed. Use str instead. The str and bytes types don’t have functionality enough in common to warrant a shared base class. The 2to3 tool (see below) replaces every occurrence of basestring with str."

**Comment by AnthonyMRios** [comment]
I'm glad you got it working. Let me know if you have any other questions.

**Comment by Pan-Qi** [comment]
Hi, 
I git clone this repo, went to the folder and run python setup.py install.
Then I run tha package, I got the same error:

Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyclausie import ClausIE
>>> cl = ClausIE.get_instance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyclausie-0.1-py3.6.egg/pyclausie/ClausIE.py", line 107, in get_instance
    return SubprocessBackend(**extra_args)
  File "/usr/local/lib/python3.6/dist-packages/pyclausie-0.1-py3.6.egg/pyclausie/SubprocessBackend.py", line 28, in __init__
    version)
  File "/usr/local/lib/python3.6/dist-packages/pyclausie-0.1-py3.6.egg/pyclausie/ClausIE.py", line 53, in __init__
    self.download_if_missing(version)
  File "/usr/local/lib/python3.6/dist-packages/pyclausie-0.1-py3.6.egg/pyclausie/ClausIE.py", line 75, in download_if_missing
    jar_url = self.get_jar_url(version)
  File "/usr/local/lib/python3.6/dist-packages/pyclausie-0.1-py3.6.egg/pyclausie/ClausIE.py", line 90, in get_jar_url
    if not isinstance(version, basestring):
NameError: name 'basestring' is not defined
>>>                               

I checked the code in the repo I cloned, it's correct 
![image](https://user-images.githubusercontent.com/43341456/64152768-a4ea7a80-ce70-11e9-8e54-a256f1b8532f.png)

Do you have any suggestions to fix this?

Thanks a lot.

**Comment by Pan-Qi** [comment]
Sloved, thanks.

**Comment by AnthonyMRios** [comment]
Awesome. Glad you figured it out!
